[tool.isort]
profile = 'black'
src_paths = ['cmnsim', 'tests', 'gateway']


[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
addopts = "--color=yes"


[tool.pydocstyle]
inherit = false
ignore = 'D100,D104,D107,D202,D203,D212,D400,D401,D405,D406,D407,D415'
match = '.*\.py'
